<?php

namespace Database\Seeders;

use App\Enums\VehicleType;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            [
                'name' => 'BMW 330i Sedan',
                'category_slug' => 'sedan',
                'type' => VehicleType::CAR,
                'price' => 2499000000,
                'deposit_amount' => 100000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => '2.0L I4 Turbo',
                    'Horsepower' => '255 hp',
                    'Torque' => '295 lb-ft',
                    '0-60mph' => '5.6s',
                    'Length_Width_Height' => '4,713 x 1,827 x 1,440 mm',
                    'Wheelbase' => '2,851 mm',
                    'Curb_Weight' => '1,650 kg',
                    'Fuel_Tank_Cap' => '59 l',
                    'Max_Power_RPM' => '255 HP @ 5,000-6,500 rpm',
                    'Max_Torque_RPM' => '400 Nm @ 1,550-4,400 rpm',
                    'Drive_Type' => 'RWD',
                    'Transmission_Type' => '8-Speed Steptronic Sport',
                    'Zero_To_Hundred' => '5.8 giây',
                    'Top_Speed_KMH' => '250 km/h',
                ],
                'image' => 'images/cars/330i/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW 530i Sedan',
                'category_slug' => 'sedan',
                'type' => VehicleType::CAR,
                'price' => 3199000000,
                'deposit_amount' => 150000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => '2.0L I4 Turbo (Mild Hybrid)',
                    'Horsepower' => '255 hp',
                    'Torque' => '295 lb-ft',
                    '0-60mph' => '5.9s',
                    'Length_Width_Height' => '5,060 x 1,900 x 1,515 mm',
                    'Wheelbase' => '2,995 mm',
                    'Curb_Weight' => '1,830 kg',
                    'Fuel_Tank_Cap' => '60 l',
                    'Max_Power_RPM' => '255 HP @ 4,700-6,500 rpm',
                    'Max_Torque_RPM' => '400 Nm @ 1,600-4,500 rpm',
                    'Drive_Type' => 'RWD',
                    'Transmission_Type' => '8-Speed Steptronic',
                    'Zero_To_Hundred' => '6.2 giây',
                    'Top_Speed_KMH' => '250 km/h',
                ],
                'image' => 'images/cars/bmw-530i-sedan/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW 550e xDrive Sedan',
                'category_slug' => 'sedan',
                'type' => VehicleType::CAR,
                'price' => 4399000000,
                'deposit_amount' => 200000000,
                'is_featured' => false,
                'specifications' => [
                    'Engine' => '3.0L I6 PHEV',
                    'Horsepower' => '483 hp (Combined)',
                    'Torque' => '516 lb-ft (Combined)',
                    '0-60mph' => '4.0s',
                    'Length_Width_Height' => '5,060 x 1,900 x 1,515 mm',
                    'Wheelbase' => '2,995 mm',
                    'Curb_Weight' => '2,155 kg',
                    'Fuel_Tank_Cap' => '60 l',
                    'Max_Power_RPM' => '483 HP @ 5,000-6,500 rpm',
                    'Max_Torque_RPM' => '700 Nm @ 1,750-4,700 rpm',
                    'Drive_Type' => 'BMW xDrive (AWD)',
                    'Transmission_Type' => '8-Speed Steptronic Sport',
                    'Zero_To_Hundred' => '4.3 giây',
                    'Top_Speed_KMH' => '250 km/h (E-mode: 140 km/h)',
                ],
                'image' => 'images/cars/bmw-550e-xdrive-sedan/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW i4 M60 Gran Coupe',
                'category_slug' => 'bmw-i',
                'type' => VehicleType::CAR,
                'price' => 4599000000,
                'deposit_amount' => 100000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => 'Dual Electric Motors',
                    'Horsepower' => '536 hp',
                    'Torque' => '586 lb-ft',
                    '0-60mph' => '3.7s',
                    'Length_Width_Height' => '4,783 x 1,852 x 1,448 mm',
                    'Wheelbase' => '2,856 mm',
                    'Curb_Weight' => '2,290 kg',
                    'Fuel_Tank_Cap' => '83.9 kWh (Battery)',
                    'Max_Power_RPM' => '536 HP',
                    'Max_Torque_RPM' => '795 Nm',
                    'Drive_Type' => 'Electric xDrive',
                    'Transmission_Type' => 'Single-speed fixed ratio',
                    'Zero_To_Hundred' => '3.9 giây',
                    'Top_Speed_KMH' => '225 km/h',
                ],
                'image' => 'images/cars/bmw-i4-m60-gran-coupe/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW X3 M50 xDrive',
                'category_slug' => 'sav',
                'type' => VehicleType::CAR,
                'price' => 3999000000,
                'deposit_amount' => 150000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => '3.0L I6 Mild Hybrid',
                    'Horsepower' => '393 hp',
                    'Torque' => '428 lb-ft',
                    '0-60mph' => '4.4s',
                    'Length_Width_Height' => '4,755 x 1,920 x 1,660 mm',
                    'Wheelbase' => '2,865 mm',
                    'Curb_Weight' => '2,050 kg',
                    'Fuel_Tank_Cap' => '65 l',
                    'Max_Power_RPM' => '393 HP @ 5,200-6,250 rpm',
                    'Max_Torque_RPM' => '580 Nm @ 1,900-4,800 rpm',
                    'Drive_Type' => 'BMW xDrive (AWD)',
                    'Transmission_Type' => '8-Speed Steptronic Sport',
                    'Zero_To_Hundred' => '4.6 giây',
                    'Top_Speed_KMH' => '250 km/h',
                ],
                'image' => 'images/cars/bmw-x3-m50-xdrive/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW M3 Sedan',
                'category_slug' => 'm-performance',
                'type' => VehicleType::CAR,
                'price' => 5499000000,
                'deposit_amount' => 250000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => '3.0L I6 M TwinPower',
                    'Horsepower' => '473 hp',
                    'Torque' => '406 lb-ft',
                    '0-60mph' => '4.1s',
                    'Length_Width_Height' => '4,794 x 1,903 x 1,433 mm',
                    'Wheelbase' => '2,857 mm',
                    'Curb_Weight' => '1,780 kg',
                    'Fuel_Tank_Cap' => '59 l',
                    'Max_Power_RPM' => '473 HP @ 6,250 rpm',
                    'Max_Torque_RPM' => '550 Nm @ 2,650-6,130 rpm',
                    'Drive_Type' => 'RWD',
                    'Transmission_Type' => '6-Speed Manual / 8-Speed M Steptronic',
                    'Zero_To_Hundred' => '4.2 giây',
                    'Top_Speed_KMH' => '290 km/h',
                ],
                'image' => 'images/cars/bmw-m3-sedan/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW M4 Coupe',
                'category_slug' => 'coupe',
                'type' => VehicleType::CAR,
                'price' => 5599000000,
                'deposit_amount' => 250000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => '3.0L I6 M TwinPower',
                    'Horsepower' => '473 hp',
                    'Torque' => '406 lb-ft',
                    '0-60mph' => '4.1s',
                    'Length_Width_Height' => '4,794 x 1,887 x 1,393 mm',
                    'Wheelbase' => '2,857 mm',
                    'Curb_Weight' => '1,775 kg',
                    'Fuel_Tank_Cap' => '59 l',
                    'Max_Power_RPM' => '473 HP @ 6,250 rpm',
                    'Max_Torque_RPM' => '550 Nm @ 2,650-6,130 rpm',
                    'Drive_Type' => 'RWD',
                    'Transmission_Type' => '6-Speed Manual / 8-Speed M Steptronic',
                    'Zero_To_Hundred' => '4.2 giây',
                    'Top_Speed_KMH' => '290 km/h',
                ],
                'image' => 'images/cars/bmw-m4-coupe/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW X5 M Competition',
                'category_slug' => 'sav',
                'type' => VehicleType::CAR,
                'price' => 6999000000,
                'deposit_amount' => 200000000,
                'is_featured' => false,
                'specifications' => [
                    'Engine' => '4.4L V8 M TwinPower',
                    'Horsepower' => '617 hp',
                    'Torque' => '553 lb-ft',
                    '0-60mph' => '3.7s',
                    'Length_Width_Height' => '4,948 x 2,015 x 1,762 mm',
                    'Wheelbase' => '2,972 mm',
                    'Curb_Weight' => '2,400 kg',
                    'Fuel_Tank_Cap' => '83 l',
                    'Max_Power_RPM' => '617 HP @ 6,000 rpm',
                    'Max_Torque_RPM' => '750 Nm @ 1,800-5,800 rpm',
                    'Drive_Type' => 'M xDrive (AWD)',
                    'Transmission_Type' => '8-Speed M Steptronic',
                    'Zero_To_Hundred' => '3.9 giây',
                    'Top_Speed_KMH' => '290 km/h',
                ],
                'image' => 'images/cars/bmw-x5-m-competition/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW XM Label',
                'category_slug' => 'sav',
                'type' => VehicleType::CAR,
                'price' => 12999000000,
                'deposit_amount' => 500000000,
                'is_featured' => false,
                'specifications' => [
                    'Engine' => '4.4L V8 PHEV',
                    'Horsepower' => '738 hp',
                    'Torque' => '738 lb-ft',
                    '0-60mph' => '3.6s',
                    'Length_Width_Height' => '5,110 x 2,005 x 1,755 mm',
                    'Wheelbase' => '3,105 mm',
                    'Curb_Weight' => '2,710 kg',
                    'Fuel_Tank_Cap' => '69 l',
                    'Max_Power_RPM' => '738 HP @ 5,600 rpm',
                    'Max_Torque_RPM' => '1,000 Nm @ 1,800-5,400 rpm',
                    'Drive_Type' => 'M xDrive (AWD)',
                    'Transmission_Type' => '8-Speed M Steptronic',
                    'Zero_To_Hundred' => '3.8 giây',
                    'Top_Speed_KMH' => '290 km/h',
                ],
                'image' => 'images/cars/bmw-xm-label/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW M5 Touring',
                'category_slug' => 'm-performance',
                'type' => VehicleType::CAR,
                'price' => 6599000000,
                'deposit_amount' => 100000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => '4.4L V8 M Hybrid',
                    'Horsepower' => '717 hp',
                    'Torque' => '738 lb-ft',
                    '0-60mph' => '3.5s',
                    'Length_Width_Height' => '5,096 x 1,970 x 1,516 mm',
                    'Wheelbase' => '3,006 mm',
                    'Curb_Weight' => '2,470 kg',
                    'Fuel_Tank_Cap' => '60 l',
                    'Max_Power_RPM' => '717 HP @ 5,600-6,500 rpm',
                    'Max_Torque_RPM' => '1,000 Nm @ 1,800-5,400 rpm',
                    'Drive_Type' => 'M xDrive (AWD)',
                    'Transmission_Type' => '8-Speed M Steptronic',
                    'Zero_To_Hundred' => '3.6 giây',
                    'Top_Speed_KMH' => '305 km/h',
                ],
                'image' => 'images/cars/bmw-m5-touring/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW G310R',
                'category_slug' => 'motorrad',
                'type' => VehicleType::MOTORBIKE,
                'price' => 189000000,
                'deposit_amount' => 10000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => '1 xy-lanh, 313cc, DOHC',
                    'Horsepower' => '34 hp',
                    'Torque' => '28 Nm',
                    '0-60mph' => '6.8s',
                    'Length_Width_Height' => '2005 x 849 x 1080 mm',
                    'Wheelbase' => '1374 mm',
                    'Curb_Weight' => '164 kg',
                    'Fuel_Tank_Cap' => '11 l',
                    'Max_Power_RPM' => '34 HP @ 9500 rpm',
                    'Max_Torque_RPM' => '28 Nm @ 7500 rpm',
                    'Drive_Type' => 'Xích',
                    'Transmission_Type' => '6 cấp',
                    'Zero_To_Hundred' => '7.0 giây',
                    'Top_Speed_KMH' => '143 km/h',
                ],
                'image' => 'images/motorbikes/bmw-g310r/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW S1000RR',
                'category_slug' => 'motorrad',
                'type' => VehicleType::MOTORBIKE,
                'price' => 959000000,
                'deposit_amount' => 50000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => '4 xy-lanh, 999cc, ShiftCam',
                    'Horsepower' => '205 hp',
                    'Torque' => '113 Nm',
                    '0-60mph' => '2.7s',
                    'Length_Width_Height' => '2073 x 826 x 1151 mm',
                    'Wheelbase' => '1441 mm',
                    'Curb_Weight' => '197 kg',
                    'Fuel_Tank_Cap' => '16.5 l',
                    'Max_Power_RPM' => '205 HP @ 13500 rpm',
                    'Max_Torque_RPM' => '113 Nm @ 11000 rpm',
                    'Drive_Type' => 'Xích',
                    'Transmission_Type' => '6 cấp',
                    'Zero_To_Hundred' => '2.8 giây',
                    'Top_Speed_KMH' => '299 km/h',
                ],
                'image' => 'images/motorbikes/bmw-s1000rr/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW R1250GS',
                'category_slug' => 'motorrad',
                'type' => VehicleType::MOTORBIKE,
                'price' => 619000000,
                'deposit_amount' => 30000000,
                'is_featured' => true,
                'specifications' => [
                    'Engine' => 'Boxer 2 xy-lanh, 1254cc',
                    'Horsepower' => '136 hp',
                    'Torque' => '143 Nm',
                    '0-60mph' => '3.4s',
                    'Length_Width_Height' => '2207 x 952 x 1430 mm',
                    'Wheelbase' => '1525 mm',
                    'Curb_Weight' => '249 kg',
                    'Fuel_Tank_Cap' => '20 l',
                    'Max_Power_RPM' => '136 HP @ 7750 rpm',
                    'Max_Torque_RPM' => '143 Nm @ 6250 rpm',
                    'Drive_Type' => 'Trục (shaft drive)',
                    'Transmission_Type' => '6 cấp',
                    'Zero_To_Hundred' => '3.5 giây',
                    'Top_Speed_KMH' => '200 km/h',
                ],
                'image' => 'images/motorbikes/bmw-r1250gs/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW F900R',
                'category_slug' => 'motorrad',
                'type' => VehicleType::MOTORBIKE,
                'price' => 459000000,
                'deposit_amount' => 20000000,
                'is_featured' => false,
                'specifications' => [
                    'Engine' => '2 xy-lanh, 895cc',
                    'Horsepower' => '105 hp',
                    'Torque' => '92 Nm',
                    '0-60mph' => '3.7s',
                    'Length_Width_Height' => '2140 x 815 x 1130 mm',
                    'Wheelbase' => '1518 mm',
                    'Curb_Weight' => '211 kg',
                    'Fuel_Tank_Cap' => '13 l',
                    'Max_Power_RPM' => '105 HP @ 8500 rpm',
                    'Max_Torque_RPM' => '92 Nm @ 6500 rpm',
                    'Drive_Type' => 'Xích',
                    'Transmission_Type' => '6 cấp',
                    'Zero_To_Hundred' => '3.8 giây',
                    'Top_Speed_KMH' => '200 km/h',
                ],
                'image' => 'images/motorbikes/bmw-f900r/hero-front-three-quarter.png',
            ],
            [
                'name' => 'BMW K1600GT',
                'category_slug' => 'motorrad',
                'type' => VehicleType::MOTORBIKE,
                'price' => 1200000000,
                'deposit_amount' => 50000000,
                'is_featured' => false,
                'specifications' => [
                    'Engine' => '6 xy-lanh thẳng hàng, 1649cc',
                    'Horsepower' => '160 hp',
                    'Torque' => '180 Nm',
                    '0-60mph' => '3.3s',
                    'Length_Width_Height' => '2340 x 1000 x 1460 mm',
                    'Wheelbase' => '1618 mm',
                    'Curb_Weight' => '343 kg',
                    'Fuel_Tank_Cap' => '26.5 l',
                    'Max_Power_RPM' => '160 HP @ 6750 rpm',
                    'Max_Torque_RPM' => '180 Nm @ 5250 rpm',
                    'Drive_Type' => 'Trục',
                    'Transmission_Type' => '6 cấp',
                    'Zero_To_Hundred' => '3.4 giây',
                    'Top_Speed_KMH' => '200 km/h',
                ],
                'image' => 'images/motorbikes/bmw-k1600gt/hero-front-three-quarter.png',
            ],

            // --- PHỤ KIỆN Ô TÔ ---
            [
                'name' => 'Thảm lót sàn M Performance',
                'category_slug' => 'phu-kien-o-to',
                'type' => VehicleType::ACCESSORY,
                'price' => 3500000,
                'deposit_amount' => 0,
                'is_featured' => true,
                'specifications' => [
                    'Material' => 'Cao su nguyên khối chống trơn',
                    'Compatibility' => 'BMW 3 Series / 5 Series / X3 / X5',
                    'Weight' => '2.5 kg/bộ',
                    'Warranty' => '12 tháng',
                ],
                'image' => 'images/accessories/tham-lot-san-m-performance/hero-product.png',
            ],
            [
                'name' => 'Camera hành trình BMW Advanced Eye 3.0',
                'category_slug' => 'phu-kien-o-to',
                'type' => VehicleType::ACCESSORY,
                'price' => 12500000,
                'deposit_amount' => 0,
                'is_featured' => true,
                'specifications' => [
                    'Resolution' => '4K Ultra HD',
                    'Field_of_View' => '170° góc rộng',
                    'Storage' => '64GB MicroSD (included)',
                    'Features' => 'GPS, G-Sensor, Night Vision, Parking Mode',
                    'Warranty' => '24 tháng',
                ],
                'image' => 'images/accessories/camera-hanh-trinh-bmw-advanced-eye-30/hero-product.png',
            ],
            [
                'name' => 'Bọc vô lăng M Performance Carbon',
                'category_slug' => 'phu-kien-o-to',
                'type' => VehicleType::ACCESSORY,
                'price' => 8900000,
                'deposit_amount' => 0,
                'is_featured' => false,
                'specifications' => [
                    'Material' => 'Alcantara + Carbon Fiber',
                    'Compatibility' => 'BMW M3 / M4 / M5 / M8',
                    'Weight' => '0.8 kg',
                    'Color' => 'Black / Red Stitching',
                    'Warranty' => '12 tháng',
                ],
                'image' => 'images/accessories/boc-vo-lang-m-performance-carbon/hero-product.png',
            ],
            [
                'name' => 'Bộ vành BMW M Performance Y-Spoke 20"',
                'category_slug' => 'phu-kien-o-to',
                'type' => VehicleType::ACCESSORY,
                'price' => 45000000,
                'deposit_amount' => 5000000,
                'is_featured' => true,
                'specifications' => [
                    'Size' => '20 x 8.5J (Front) / 20 x 9.5J (Rear)',
                    'Material' => 'Forged Aluminum Alloy',
                    'Finish' => 'Jet Black / Polished',
                    'Compatibility' => 'BMW 3 Series (G20) / 4 Series (G22)',
                    'Weight' => '9.2 kg/vành',
                    'Warranty' => '24 tháng',
                ],
                'image' => 'images/accessories/bo-vanh-bmw-m-performance-y-spoke-20/hero-product.png',
            ],
            [
                'name' => 'Bộ đèn LED nội thất Ambient Light Pro',
                'category_slug' => 'phu-kien-o-to',
                'type' => VehicleType::ACCESSORY,
                'price' => 6200000,
                'deposit_amount' => 0,
                'is_featured' => false,
                'specifications' => [
                    'Colors' => '64 màu tùy chỉnh',
                    'Zones' => '11 vùng chiếu sáng',
                    'Compatibility' => 'BMW 5 Series / X5 / 7 Series',
                    'Control' => 'BMW iDrive / BMW Connected App',
                    'Warranty' => '12 tháng',
                ],
                'image' => 'images/accessories/bo-den-led-noi-that-ambient-light-pro/hero-product.png',
            ],

            // --- PHỤ KIỆN XE MÁY ---
            [
                'name' => 'Thùng nhôm BMW Motorrad Vario 35L',
                'category_slug' => 'phu-kien-xe-may',
                'type' => VehicleType::ACCESSORY,
                'price' => 15800000,
                'deposit_amount' => 0,
                'is_featured' => true,
                'specifications' => [
                    'Capacity' => '35 Lít (mỗi bên)',
                    'Material' => 'Nhôm nguyên khối',
                    'Compatibility' => 'BMW R1250GS / R1300GS / F850GS',
                    'Lock' => 'Khóa thống nhất BMW (One-key system)',
                    'Weight' => '4.8 kg/thùng',
                    'Warranty' => '24 tháng',
                ],
                'image' => 'images/accessories/thung-nhom-bmw-motorrad-vario-35l/hero-product.png',
            ],
            [
                'name' => 'Mũ bảo hiểm BMW System 7 Carbon',
                'category_slug' => 'phu-kien-xe-may',
                'type' => VehicleType::ACCESSORY,
                'price' => 22500000,
                'deposit_amount' => 0,
                'is_featured' => true,
                'specifications' => [
                    'Shell' => 'Carbon Fiber',
                    'Weight' => '1.590 kg (size M)',
                    'Certification' => 'ECE 22.06',
                    'Features' => 'Lật hàm, kính chống sương, Bluetooth-ready',
                    'Sizes' => 'XS - XXL',
                    'Warranty' => '24 tháng',
                ],
                'image' => 'images/accessories/mu-bao-hiem-bmw-system-7-carbon/hero-product.png',
            ],
            [
                'name' => 'Ốp Carbon bảo vệ động cơ S1000RR',
                'category_slug' => 'phu-kien-xe-may',
                'type' => VehicleType::ACCESSORY,
                'price' => 7800000,
                'deposit_amount' => 0,
                'is_featured' => false,
                'specifications' => [
                    'Material' => 'Carbon Fiber 3K Twill Weave',
                    'Compatibility' => 'BMW S1000RR (2023+)',
                    'Parts' => 'Nắp đậy bình xăng, ốp hông, chắn gió',
                    'Weight' => '0.4 kg/bộ',
                    'Warranty' => '12 tháng',
                ],
                'image' => 'images/accessories/op-carbon-bao-ve-dong-co-s1000rr/hero-product.png',
            ],
            [
                'name' => 'Áo giáp BMW Motorrad StreetGuard',
                'category_slug' => 'phu-kien-xe-may',
                'type' => VehicleType::ACCESSORY,
                'price' => 18900000,
                'deposit_amount' => 0,
                'is_featured' => true,
                'specifications' => [
                    'Material' => 'GORE-TEX® Pro',
                    'Protection' => 'CE Level 2 (Vai, Khuỷu tay, Lưng)',
                    'Features' => 'Chống nước, chống gió, thoáng khí 4 mùa',
                    'Sizes' => 'S - 3XL',
                    'Warranty' => '24 tháng',
                ],
                'image' => 'images/accessories/ao-giap-bmw-motorrad-streetguard/hero-product.png',
            ],
            [
                'name' => 'Bộ bảo vệ gầm BMW Motorrad Enduro',
                'category_slug' => 'phu-kien-xe-may',
                'type' => VehicleType::ACCESSORY,
                'price' => 5600000,
                'deposit_amount' => 0,
                'is_featured' => false,
                'specifications' => [
                    'Material' => 'Nhôm CNC 4mm',
                    'Compatibility' => 'BMW R1250GS Adventure / R1300GS',
                    'Weight' => '3.2 kg',
                    'Protection' => 'Carter dầu, ống xả, hộp số',
                    'Warranty' => '24 tháng',
                ],
                'image' => 'images/accessories/bo-bao-ve-gam-bmw-motorrad-enduro/hero-product.png',
            ],
        ];

        foreach ($vehicles as $vehicleData) {
            // Robust category matching
            $category = Category::where('slug', $vehicleData['category_slug'])->first();

            // If category doesn't exist yet, fallback to the first available category or a default
            $categoryId = $category ? $category->id : (Category::first()->id ?? 1);

            $product = Product::updateOrCreate(
                ['slug' => Str::slug($vehicleData['name'])],
                [
                    'category_id' => $categoryId,
                    'name' => $vehicleData['name'],
                    'type' => $vehicleData['type'],
                    'price' => $vehicleData['price'],
                    'deposit_amount' => $vehicleData['deposit_amount'],
                    'specifications' => $vehicleData['specifications'],
                    'is_featured' => $vehicleData['is_featured'],
                    'is_active' => true,
                    'stock' => 10,
                    'description' => "Trải nghiệm đỉnh cao công xưởng Đức với mẫu {$vehicleData['name']} thế hệ mới 2025. Hiệu năng vượt trội, công nghệ dẫn đầu.",
                ]
            );

            $product->images()
                ->where('is_primary', true)
                ->where('path', '!=', $vehicleData['image'])
                ->update(['is_primary' => false]);

            $product->images()->updateOrCreate(
                ['path' => $vehicleData['image']],
                ['is_primary' => true, 'sort_order' => 0]
            );
        }
    }
}
